from __future__ import annotations

from codesync import config as cfg_mod
from codesync import git_ops, output, status as status_mod


def run_sync(status_only: bool = False, workers: int | None = None,
             problems_only: bool = False, no_publish: bool = False,
             no_push: bool = False, no_commit: bool = False,
             skip_version_check: bool = False) -> int:
    """The one-command sync (v2.3.0+).

    Default flow does everything: clone missing GitHub repos, publish local
    orphans, pull, auto-commit, push local commits. Opt out of pieces with
    no_publish / no_push. status_only short-circuits to a read-only report.

    push is the DEFAULT now (was opt-in via --push pre-v2.3.0). This matches the
    "I want every local change uploaded without thinking about it" workflow.
    """
    do_push = not no_push

    # 1. load config
    cfg = cfg_mod.load()

    # 1a. Show current + latest version up front, on every run incl. --status
    #     (v2.10.0). Cheap/fail-open; the gate below reuses the cached lookup.
    from codesync.updater import print_version_status
    print_version_status(cfg.update)

    # 1b. Version gate (v2.7.0): refuse to run destructive sync on an outdated
    #     codesync. Read-only --status is exempt. Fails open on network errors;
    #     --skip-version-check bypasses; [update] config can disable/soften it.
    if not status_only:
        from codesync.updater import enforce_up_to_date
        if not enforce_up_to_date(cfg.update, skip=skip_version_check):
            return 1

    # 2. GitHub auto-clone (only if configured; gh auth happens inside).
    #    push mode here controls whether locally-deleted repos get archived on GitHub.
    #    SKIPPED in --status mode: status is strictly read-only (no gh calls, no
    #    clone, no archive). auto_clone clones/archives, which is a write.
    migrations: list[tuple[str, str]] = []
    if cfg.auto_clone and not status_only:
        from codesync import github_auto, rename as rename_mod
        auto_migrate = (cfg.rename is None) or cfg.rename.auto_migrate
        claude_projects = rename_mod._resolve_claude_projects(cfg.rename)
        migrations = github_auto.run(
            cfg.auto_clone, cfg.code_roots_expanded,
            push=do_push, auto_migrate=auto_migrate,
            claude_projects=claude_projects,
        )
    elif cfg.auto_clone is None and not status_only:
        # Silent feature-absence reads as success: a config without [auto_clone]
        # (e.g. generated by V1 migrate-config) syncs fine but never clones repos
        # created on other machines — and nothing ever said so. One dim line, not
        # a warn, so deliberate gh-free workflows aren't nagged. (v2.14.0)
        output.detail("（未配置 [auto_clone]，其他机器新建的 repo 不会自动克隆到本机 —— `codesync init` 可补）")

    # 2b. Publish local orphans (dirs with no .git, or .git without origin).
    #     Skipped in status-only mode (read-only) and when --no-publish given.
    if not status_only and not no_publish:
        from codesync import publish
        publish.publish_orphans(cfg)

    # 3. discover repos (AFTER publish, so freshly-published repos are included)
    toplevel = git_ops.find_repos(cfg.code_roots_expanded)
    output.section("扫描代码目录")
    for root in cfg.code_roots_expanded:
        if root.exists():
            output.detail(f"扫描 {root}")
        else:
            output.detail(f"跳过不存在的目录 {root}")
    output.detail(f"发现 {len(toplevel)} 个 repo")

    # 3a. half-deleted .git husks (v2.16.0): a dir whose .git lost HEAD —
    #     typically a manual delete that skipped read-only pack files. git
    #     rejects every op on it; surface it ONCE with a cleanup hint instead
    #     of letting publish/pull/push each fail on "not a git repository".
    corrupt = git_ops.find_corrupt_repos(cfg.code_roots_expanded)
    if corrupt:
        output.warn(f"{len(corrupt)} 个目录的 .git 残缺（疑似删除未完成留下的残骸），已跳过同步:")
        for c in corrupt:
            output.warn(f"  {c.name}  →  清理: codesync delete {c.name}（只删本地）")

    # 3b. discover nested repos (v2.8.0). EMBEDDED repos sync as independent
    #     repos (third-party = pull-only); PROPER submodules get a submodule
    #     update after pull. The outer repo's auto-commit excludes the nested
    #     path so a moving gitlink isn't baked into the superproject.
    recurse = (cfg.submodules is None) or cfg.submodules.recurse
    sub_skip = tuple(cfg.submodules.skip) if cfg.submodules else ()
    embedded: list[git_ops.NestedRepo] = []
    submodule_parents: list = []
    if recurse:
        owners = git_ops.my_owners(cfg, toplevel)
        nested = git_ops.find_nested_repos(toplevel, owners, skip=sub_skip)
        embedded = [n for n in nested if not n.is_submodule]
        submodule_parents = [r for r in toplevel if (r / ".gitmodules").exists()]
        if embedded or submodule_parents:
            n_push = sum(1 for e in embedded if e.pushable)
            n_pull = len(embedded) - n_push
            output.detail(
                f"嵌套 repo：{len(embedded)} 个嵌入式（{n_push} 可同步 / "
                f"{n_pull} 第三方 pull-only），{len(submodule_parents)} 个含 submodule"
            )

    # Repos for each phase:
    #   pull  : every repo (top-level + all embedded; third-party pulled too)
    #   commit/push : top-level + embedded that are mine (pull-only ones skipped)
    embedded_all = [e.path for e in embedded]
    embedded_pushable = [e.path for e in embedded if e.pushable]
    pull_repos = toplevel + embedded_all
    push_repos = toplevel + embedded_pushable
    # outer-repo → nested rel paths to keep out of the outer's auto-commit
    exclude_map: dict = {}
    for e in embedded:
        exclude_map.setdefault(e.outer, set()).add(e.rel)

    workers = workers or git_ops.default_workers()

    # 3c. duplicate-origin advisory (v2.14.0): the same remote checked out into
    #     2+ top-level folders (old date-prefixed clone + canonical clone) wastes
    #     disk and risks editing the wrong copy. Top-level only — embedded repos
    #     sharing their outer's origin is a separate (known) shape. Read-only:
    #     report, never auto-fix.
    dup_origins = git_ops.find_duplicate_origins(toplevel, max_workers=workers)
    if dup_origins:
        output.warn(f"{len(dup_origins)} 个 origin 被多个本地目录共用（同一 repo 克隆了多份，建议保留一份）:")
        for origin_key, repo_paths in sorted(dup_origins.items()):
            names = ", ".join(p.name for p in repo_paths)
            output.detail(f"  {origin_key}  ←  {names}")

    # 4. status-only mode
    if status_only:
        output.section("repo 状态")
        status_mod.print_status(pull_repos, problems_only=problems_only, max_workers=workers)
        return 0

    # 5. parallel pull (top-level + all embedded, third-party included)
    output.section(f"并发 pull (workers={workers})")
    pull_summary = git_ops.parallel_op(pull_repos, "pull", max_workers=workers)
    git_ops.print_summary(pull_summary)

    # 5a. proper submodules: check out recorded commits after the parent's pull.
    if submodule_parents:
        git_ops.update_submodules(submodule_parents, max_workers=workers)

    # 5c. auto-commit dirty repos (default on; --no-commit / [commit].enabled=false to skip).
    #     Runs AFTER pull (commit lands on top of remote) and BEFORE push (gets pushed).
    commit_enabled = (cfg.commit is None) or cfg.commit.enabled
    if not no_commit and commit_enabled:
        skip_names = set(cfg.commit.skip) if cfg.commit else {"dev-tools"}
        output.section("自动提交本地改动")
        # Commit top-level + my embedded repos (not third-party pull-only ones);
        # exclude_map keeps nested gitlinks out of the outer repos' commits.
        committed = git_ops.auto_commit_dirty(
            push_repos, skip_names, max_workers=workers, exclude_map=exclude_map,
        )
        if committed:
            output.detail(f"已 commit {len(committed)} 个 repo（将随 push 上传）")

    # 6. push (default; skip with --no-push). Top-level + my embedded repos.
    push_summary = None
    if do_push:
        output.section(f"并发 push (workers={workers})")
        push_summary = git_ops.parallel_op(push_repos, "push", max_workers=workers)
        git_ops.print_summary(push_summary)
    else:
        output.detail("(--no-push：跳过推送)")

    # 6c. Highlight cross-machine renames picked up this run, so the changed repo
    #     name doesn't slip by unnoticed in the scroll-back.
    if migrations:
        output.section("⚠ 检测到其他机器改名（本机已自动迁移）")
        for old, new in migrations:
            output.info(output.hilite(f"  {old}  →  {new}", "yellow"))

    # 7. final status summary
    output.section("状态总览")
    status_mod.print_status(pull_repos, problems_only=problems_only, max_workers=workers)

    # Bubble up failure if any repo failed.
    if pull_summary.failed:
        return 2
    if push_summary is not None and push_summary.failed:
        return 2
    return 0
