"""First-run setup wizard.

When `codesync sync` runs without a config file, this guides the user through
a minimal interactive setup instead of dumping a "go edit this TOML" message.
The whole point is that a fresh `curl ... install.sh | bash` → `codesync sync`
flow should reach a working state without the user opening a text editor.

Flow:
    1. Try to detect gh auth (kicking off `gh auth login --web` if needed).
    2. Pull the user's GitHub login via `gh api user`.
    3. Print the proposed config (sensible defaults: ~/SyncRepos for both
       code_roots and auto_clone.target, auto_clone enabled with their login).
    4. Ask for confirmation (Y default; non-tty → Y silently).
    5. Write a fully-populated TOML and return True.

Returns False if any step fails — caller then falls back to writing the
empty template (current pre-v2.2.6 behavior) so the user can hand-edit.
"""
from __future__ import annotations

from pathlib import Path

from codesync import auth, config, output, paths


def _prompt_yes(question: str) -> bool:
    """Read one line of user input, treating empty / EOF as Yes (default).
    Anything starting with 'n' or 'N' is No."""
    try:
        ans = input(question).strip().lower()
    except EOFError:
        # Non-interactive stdin (piped). Default to Yes — script was invoked
        # by an automated install flow that wants reasonable defaults.
        return True
    return not ans.startswith("n")


def _build_initial_toml(owner: str, target: Path) -> str:
    """Render a TOML config string with owner / target filled in.
    Uses _toml_str so Windows paths survive the basic-string `\\U` escape pitfall."""
    t = config._toml_str(str(target))
    return f"""\
# codesync config — generated by first-run wizard.
# Edit any time. Re-run `codesync sync` after changes.

code_roots = [
    {t},
]

[auto_clone]
owner               = {config._toml_str(owner)}
target              = {t}
skip                = []
skip_confirmation   = false
abort_if_shrink_pct = 20
include_forks       = true

# Optional: Docker MySQL cross-PC sync via Dropbox.
# Add one [[db_sync]] block per database. Example:
# [[db_sync]]
# name      = "myproject"
# container = "myproject-mysql-dev"
# database  = "myproject_db"
# user      = "myproject_user"
# password  = "dev_pwd"
# dump_file = "~/Dropbox/db-sync/myproject.sql"
"""


def run_first_run_wizard() -> bool:
    """Returns True if a complete config was written, False if caller should
    fall back to template-only behavior."""
    output.section("首次运行配置向导")
    output.info("  没找到 config，先帮你生成一份。")

    if not auth.gh_available():
        output.warn("gh CLI 未装 — 无法自动检测 GitHub 账号。")
        output.detail("  Mac:     brew install gh")
        output.detail("  Windows: winget install GitHub.cli")
        output.detail("  装好 gh 后重跑 `codesync sync`，或手动编辑 config.toml。")
        return False

    # ensure_gh_authenticated runs `gh auth login --web` interactively if needed.
    if not auth.ensure_gh_authenticated():
        output.warn("GitHub 认证未完成 — 跳过自动配置。")
        return False

    owner = auth.gh_username()
    if not owner:
        output.warn("无法读取 GitHub 用户名（gh api user 失败）。")
        return False

    target = Path.home() / "SyncRepos"

    output.info("")
    output.info("  根据你的 gh 登录，建议如下配置：")
    output.detail(f"    code_roots        = [{target}]")
    output.detail(f"    auto_clone.owner  = {owner}")
    output.detail(f"    auto_clone.target = {target}")
    output.detail(f"    db_sync           = (空，未来需要时手动加)")
    output.info("")
    output.info(f"  跑这套配置会做一件事：把你 github.com/{owner} 名下所有")
    output.info(f"  非 fork、非 archive 的 repo 自动 clone 到 {target}/")
    output.info("")

    if not _prompt_yes("  继续吗？[Y/n] "):
        output.info("已取消。")
        output.detail(f"如果想手动编辑，模板路径：{paths.config_file()}")
        return False

    paths.ensure_config_dir()
    target.mkdir(parents=True, exist_ok=True)
    paths.config_file().write_text(_build_initial_toml(owner, target), encoding="utf-8")
    output.good(f"已写入 {paths.config_file()}")
    output.detail("继续跑 sync —— auto_clone 会拉取你的 GitHub repo。")
    return True
