"""First-run setup wizard.

When `codesync sync` runs without a config file, this guides the user through
a minimal interactive setup instead of dumping a "go edit this TOML" message.
The whole point is that a fresh `curl ... install.sh | bash` → `codesync sync`
flow should reach a working state without the user opening a text editor.

Flow:
    1. Try to detect gh auth (kicking off `gh auth login --web` if needed).
    2. Pull the user's GitHub login via `gh api user`.
    3. Print the proposed config (sensible defaults: ~/SyncRepos for both
       code_roots and auto_clone.target, auto_clone enabled with their login).
    4. Ask for confirmation (Y default; non-tty → Y silently).
    5. Write a fully-populated TOML and return True.

Returns False if any step fails — caller then falls back to writing the
empty template (current pre-v2.2.6 behavior) so the user can hand-edit.
"""
from __future__ import annotations

import os
import stat
from pathlib import Path

from codesync import auth, config, output, paths


def _prompt_yes(question: str) -> bool:
    """Read one line of user input, treating empty / EOF as Yes (default).
    Anything starting with 'n' or 'N' is No. Ctrl+C is No (not a traceback)."""
    try:
        ans = input(question).strip().lower()
    except EOFError:
        # Non-interactive stdin (piped). Default to Yes — script was invoked
        # by an automated install flow that wants reasonable defaults.
        return True
    except KeyboardInterrupt:
        # Ctrl+C at the prompt = decline, cleanly (a raw traceback here reads
        # as a crash to a first-run user).
        print()
        return False
    return not ans.startswith("n")


def _prompt_explicit_yes(question: str) -> bool:
    """Prompt for a state-changing repair; empty input and EOF mean No."""
    try:
        answer = input(question).strip().lower()
    except (EOFError, KeyboardInterrupt):
        print()
        return False
    return answer in {"y", "yes", "是"}


def _split_code_roots(raw: str) -> list[str]:
    roots: list[str] = []
    seen: set[str] = set()
    for item in raw.split(";"):
        configured = item.strip().strip('"').strip("'")
        if not configured:
            continue
        identity = os.path.normcase(str(Path(paths.expand(configured))))
        if identity not in seen:
            roots.append(configured)
            seen.add(identity)
    return roots


def repair_code_roots(
    cfg: config.Config,
    problems: list[config.CodeRootProblem],
) -> bool:
    """Interactively replace invalid roots while preserving the rest of config."""
    output.info("")
    if not _prompt_explicit_yes("  是否现在修复 code_roots？[y/N] "):
        output.info("未修改配置。")
        return False

    output.info("  请输入实际代码目录；多个目录使用分号分隔。")
    output.detail(r"例如：V:\SyncRepos")
    try:
        raw = input("  新的 code_roots: ").strip()
    except (EOFError, KeyboardInterrupt):
        print()
        output.info("未修改配置。")
        return False

    roots = _split_code_roots(raw)
    if not roots:
        output.warn("没有输入有效目录，配置未修改。")
        return False

    expanded_roots: list[Path] = []
    for configured in roots:
        expanded = Path(paths.expand(configured))
        try:
            mode = expanded.stat().st_mode
        except FileNotFoundError:
            output.warn(f"目录不存在，配置未修改: {expanded}")
            return False
        except (OSError, ValueError) as exc:
            output.warn(f"目录不可访问，配置未修改: {expanded} ({exc})")
            return False
        if not stat.S_ISDIR(mode):
            output.warn(f"路径不是目录，配置未修改: {expanded}")
            return False
        expanded_roots.append(expanded)

    invalid_paths = {
        os.path.normcase(str(problem.expanded))
        for problem in problems
        if problem.expanded is not None
    }
    cfg.code_roots = roots
    if cfg.auto_clone is not None:
        target = Path(paths.expand(cfg.auto_clone.target))
        try:
            target_is_dir = target.is_dir()
        except (OSError, ValueError):
            target_is_dir = False
        if os.path.normcase(str(target)) in invalid_paths or not target_is_dir:
            cfg.auto_clone.target = roots[0]

    backup = config.save(cfg, backup=True)
    output.good(f"已更新 {paths.config_file()}")
    if backup is not None:
        output.detail(f"原配置备份: {backup}")
    for expanded in expanded_roots:
        output.detail(f"有效代码目录: {expanded}")
    return True


def _build_initial_toml(owner: str, target: Path) -> str:
    """Render a TOML config string with owner / target filled in.
    Uses _toml_str so Windows paths survive the basic-string `\\U` escape pitfall."""
    t = config._toml_str(str(target))
    return f"""\
# codesync config — generated by first-run wizard.
# Edit any time. Re-run `codesync sync` after changes.

code_roots = [
    {t},
]

[auto_clone]
owner               = {config._toml_str(owner)}
target              = {t}
skip                = []
skip_confirmation   = false
abort_if_shrink_pct = 20
include_forks       = true

[publish]
skip              = []
skip_confirmation = false

[commit]
enabled = true
skip    = ['dev-tools']
"""


def run_first_run_wizard() -> bool:
    """Returns True if a complete config was written, False if caller should
    fall back to template-only behavior."""
    output.section("首次运行配置向导")
    output.info("  没找到 config，先帮你生成一份。")

    if not auth.gh_available():
        output.warn("gh CLI 未装 — 无法自动检测 GitHub 账号。")
        output.detail("  Mac:     brew install gh")
        output.detail("  Windows: winget install GitHub.cli")
        output.detail("  装好 gh 后重跑 `codesync sync`，或手动编辑 config.toml。")
        return False

    # ensure_gh_authenticated runs `gh auth login --web` interactively if needed.
    if not auth.ensure_gh_authenticated():
        output.warn("GitHub 认证未完成 — 跳过自动配置。")
        return False

    owner = auth.gh_username()
    if not owner:
        output.warn("无法读取 GitHub 用户名（gh api user 失败）。")
        return False

    target = Path.home() / "SyncRepos"

    output.info("")
    output.info("  根据你的 gh 登录，建议如下配置：")
    output.detail(f"    code_roots        = [{target}]")
    output.detail(f"    auto_clone.owner  = {owner}")
    output.detail(f"    auto_clone.target = {target}")
    output.info("")
    output.info(f"  跑这套配置会做一件事：把你 github.com/{owner} 名下所有")
    output.info(f"  非 fork、非 archive 的 repo 自动 clone 到 {target}/")
    output.info("")

    if not _prompt_yes("  继续吗？[Y/n] "):
        output.info("已取消。")
        output.detail(f"如果想手动编辑，模板路径：{paths.config_file()}")
        return False

    paths.ensure_config_dir()
    target.mkdir(parents=True, exist_ok=True)
    paths.config_file().write_text(_build_initial_toml(owner, target), encoding="utf-8")
    output.good(f"已写入 {paths.config_file()}")
    output.detail("继续跑 sync —— auto_clone 会拉取你的 GitHub repo。")
    return True
